# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f9fdf231d42505566b3686fd5dafea010b212f83d5e4ef2d9fcccd84feb70bb369236bf80fae538093d1373d292377bc15ffc4f8150a1d5344d46ac32db73ee

test:
  secret_key_base: 0fd7fdb4d0c9c5bdfd69f91d26ca5cf67676a7b7ef53fd06f590b88eedcdcfd4d34050e31b09196627e7211b891c6aa7da2f0d7580d384b00815029bad62e2a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
